# GLERL Water Temperature Data Parser
---
### Carter J. Humphreys
Email: [chumphre@oswego.edu](mailto:chumphre@oswego.edu) | GitHub:[@HumphreysCarter](https://github.com/HumphreysCarter) | Website: [carterhumphreys.com](http://carterhumphreys.com/)

In [96]:
import pandas as pd
from datetime import datetime

In [97]:
dataDir='../data/WATER_TEMP/'
df = pd.DataFrame()
for year in range(2015, 2020):  
    tmp_df = pd.read_csv(f'{dataDir}/glsea-temps{year}_1024.dat', skiprows=[0,1,2,3,4,5,6,8,9], delim_whitespace=True) 
    
    if len(df.values) == 0:
        df = tmp_df
    else:
        df=df.append(tmp_df)

#df.to_csv('GreatLakesWaterTemp_2015-2019', index=False) 
years = df['Year'].values
days = df['Day'].values
dates = []

for year, day in zip(years, days):
    dates.append(datetime.strptime(f'{year}_{day}', '%Y_%j'))

df.insert(0, 'Date', dates)
df=df.drop(['Year', 'Day'], axis=1)
df=df.rename(columns={'Sup.':'Superior Lake', 'Mich.':'Lake Michigan', 'Huron':'Lake Huron', 'Erie':'Lake Erie', 'Ont.':'Lake Ontario', 'St.Clr':'Lake Saint Clair'})
df

,Date,Superior Lake,Lake Michigan,Lake Huron,Lake Erie,Lake Ontario,Lake Saint Clair
0,2015-01-01,2.59,3.53,3.26,3.33,4.43,2.32
1,2015-01-02,2.46,3.50,3.17,3.31,4.32,1.80
2,2015-01-03,2.36,3.49,3.05,3.26,4.28,0.92
3,2015-01-04,2.18,3.36,2.68,3.28,4.23,1.74
4,2015-01-05,2.06,3.16,2.42,3.01,4.04,0.22
...,...,...,...,...,...,...,...
360,2019-12-27,3.36,4.47,3.73,4.09,4.54,2.48
361,2019-12-28,3.37,4.36,3.69,4.05,4.50,2.66
362,2019-12-29,3.36,4.32,3.65,4.03,4.48,2.77
363,2019-12-30,3.34,4.28,3.62,4.01,4.47,2.85
364,2019-12-31,3.29,4.21,3.57,3.91,4.45,2.78